name: ci

on:
  pull_request:
    branches:
      - k8s
  push:
    branches:
      - k8s

#on: [push]

jobs:
  build-updns-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: usableprivacy
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      -
        name: Build cryptodns
        uses: docker/build-push-action@v2
        with:
          context: ./cryptodns
          file: ./cryptodns/Dockerfile
          platforms: linux/amd64, linux/arm
          push: true
          tags: |
            ghcr.io/usableprivacy/dns/cryptodns:k8s
      -
        name: Build letsencrypt
        uses: docker/build-push-action@v2
        with:
          context: ./letsencrypt
          file: ./letsencrypt/Dockerfile
          platforms: linux/amd64, linux/arm
          push: true
          tags: |
            ghcr.io/usableprivacy/dns/letsencrypt:k8s
      -
        name: Build recursor
        uses: docker/build-push-action@v2
        with:
          context: ./recursor
          file: ./recursor/Dockerfile
          platforms: linux/amd64, linux/arm
          push: true
          tags: |
            ghcr.io/usableprivacy/dns/recursor:k8s
